### ISSUE TITLE
Highlight current argument in documentation

### ISSUE THREAD

**Issue by gegoune** [hrsh7th/cmp-nvim-lsp-signature-help#1]
Hey, that's very promising, thanks! Do you think it's possible to highlight current argument so it's easier to find it?

**Comment by hrsh7th** [comment]
This is very difficult to implement perfectly.

BTW, We already highlight the current argument in markdown syntax.
https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/blob/main/lua/cmp_nvim_lsp_signature_help/init.lua#L102

**Comment by gegoune** [comment]
Ah, true, did not notice as it looks very subtle on my colorscheme:

nordic.nvim
<img width="494" alt="Screenshot 2021-12-01 at 08 18 51" src="https://user-images.githubusercontent.com/69750637/144182277-7255ffca-c600-4b49-b784-40831fdc67b7.png">

tokyonight.nvim
<img width="509" alt="Screenshot 2021-12-01 at 08 20 02" src="https://user-images.githubusercontent.com/69750637/144182418-55f81908-d126-42d4-ad21-1e64ed970175.png">

(in both cases middle argument is highlighted)

**Comment by max397574** [comment]
Which highlight group is used for this?

**Comment by hrsh7th** [comment]
This is depending on the markdown syntax. I'm using `\`` as highlight.

**Comment by max397574** [comment]
okay thank you very much

**Comment by rebelot** [comment]
> This is depending on the markdown syntax. I'm using ` as highlight.

I think that uses `markdownBold`

**Comment by hrsh7th** [comment]
I've improved the highlight.
If your problem would be solved by this, feel free to close this.

https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/commit/3f486a300c7f7296719c0705117afe24e3985766

**Comment by gegoune** [comment]
It is better now, thank you @hrsh7th!
