### ISSUE TITLE
Include short documentation for the current parameter

### ISSUE THREAD

**Issue by mikehaertl** [hrsh7th/cmp-nvim-lsp-signature-help#10]
Would it be possible to include a short help for the current parameter? Similar to how https://github.com/ray-x/lsp_signature.nvim does it:

![image](https://user-images.githubusercontent.com/675062/163231480-09b6af34-a0db-4821-bb25-076513a59436.png)

The same function looks like this in cmp-nvim-lsp-signature-help:

![image](https://user-images.githubusercontent.com/675062/163232333-7b14df34-c538-443b-a4c3-40c048d4cc9a.png)

Maybe this could be a configurable option?

**Comment by n3wborn** [comment]
I've just discovered this repo today which I really prefer to lsp_signature. This feature is the only thing I'd miss.
I'd love to be able to make a PR but my lua is so bad that I already struggle configuring nvim with it ^^

**Comment by mikehaertl** [comment]
I just did a very hackish implementation in #14 . I had no time to read much into nvim lua so my implementation isn't perfect for sure - but it works for me.

**Comment by mikehaertl** [comment]
This has now been merged. @hrsh7th actually improved my solution a bit and it looks good.
