### ISSUE TITLE
python print function 

### ISSUE THREAD

**Issue by forestchen1224** [hrsh7th/cmp-nvim-lsp-signature-help#16]
![cmp_signature_bug](https://user-images.githubusercontent.com/29419084/176394234-813abf9b-2f58-42ff-8aaf-e469fef2424b.png)
the signature help does not advance

**Comment by hrsh7th** [comment]
it's depending on to the LanguageServer. I can't solve it in this repo. Sorry.

**Comment by vimchun** [comment]
Hi @forestchen1224, do you still have the same behavior ?
I still reproduce it on python files with pyright LSP (the first parameter is always highlighted).

(but that works well for example on lua files with lua_ls LSP)
