### ISSUE TITLE
Suggested items become active text with overloaded functions

### ISSUE THREAD

**Issue by kubil6y** [hrsh7th/cmp-nvim-lsp-signature-help#19]
![Peek 2022-07-29 23-33](https://user-images.githubusercontent.com/71182919/181839743-2623b0e4-64b9-40c0-ae6e-f3ebc20a71c8.gif)

does this happen to your setup also?

**Comment by thekaganugur** [comment]
Yes. This is probably because of 
`		["<Tab>"] = cmp.mapping(function(fallback)
			if cmp.visible() then
				cmp.select_next_item()
			elseif luasnip.expand_or_jumpable() then
				luasnip.expand_or_jump()
			elseif has_words_before() then
				cmp.complete()
			else
				fallback()
			end
		end, { "i", "s" }),
`
in my case and there should be a if check but my lua/neovim is not that good.
