### ISSUE TITLE
Weird "Text" at the end

### ISSUE THREAD

**Issue by lazywei** [hrsh7th/cmp-nvim-lsp-signature-help#24]
For some reason I'm getting this "Text" at the end of the signature help. It's showing up for every kind of arguments so I don't think this is something related to the typing.

If I invoke `:lua vim.lsp.buf.signature_help()` then it's working as expected (i.e., no "Text" at the end).

Is this coming from this plugin or is this coming from my lsp directly (as reference, i'm using `gopls` for Go)

![image](https://user-images.githubusercontent.com/2840571/198151379-9e8932e2-ab5c-4a17-bfb5-8635d80ac25a.png)

**Comment by hrsh7th** [comment]
This is nvim-cmp's kind field. You can remove kind field from completion menu.
See `:help cmp-config.formatting.fields`

**Comment by lazywei** [comment]
Got it. I managed to use use https://github.com/onsails/lspkind.nvim to generate the formatting settings. Thank you!!
