### ISSUE TITLE
Wrong cmp `format` "kind" for suggested signature

### ISSUE THREAD

**Issue by 0-th** [hrsh7th/cmp-nvim-lsp-signature-help#27]
![image](https://user-images.githubusercontent.com/65789190/209494208-aa4e58df-0b54-4aed-b90a-b625de95dc7a.png)
The suggested signature uses the wrong cmp `format` kind and displays suggestions as **Text**, inherently selecting my specified kind icon for *Text*. 
Is there a way around this from my end, or will there be a fix with subsequent updates?

**Comment by Xiione** [comment]
Hey, did you end up finding a solution to this issue?

**Comment by 0-th** [comment]
Yh, I think I did. Hence, the closing of the issue.
iirc, the problem was from my end.

**Comment by Xiione** [comment]
Got it. I'll see what fixes it in my case and post it here for others
