### ISSUE TITLE
No longer seeing signature help with elixir-ls on function completion

### ISSUE THREAD

**Issue by fmoda3** [hrsh7th/cmp-nvim-lsp-signature-help#7]
Before the recent commit that ignores TriggerOnly (414619286928901600cf5b5ccb2f62666f82d3bd), I would get signature help on function completions from elixir-ls, but after the commit, I no longer do.  Is this the intended behavior of the change?

**Comment by hrsh7th** [comment]
I've reverted the codes. THank you for reporting.
